export const START_CAPACITY = 10;
export const START_USER_STORY_CHANCE = 30;
export const START_GREMLIN_CHANCE = 0;
export const GAME_ROUNDS = 8;
export const INTERACTIVE_TRAILING_ROUNDS = 3;
export const SIMULATED_TRAILING_ROUNDS = 3;
export const EFFECT_HIDDEN = Symbol('EFFECT_HIDDEN');

export const TOTAL_INTERACTIVE_ROUNDS =
  GAME_ROUNDS + INTERACTIVE_TRAILING_ROUNDS;
export const TOTAL_ROUNDS =
  TOTAL_INTERACTIVE_ROUNDS + SIMULATED_TRAILING_ROUNDS;
